livegoods:
  search:
    init:
      enabled: true # 配置是否需要初始化索引，创建和设置映射。默认为false
spring:
  profiles:
    active: mongodb, bannerNginx
  application:
    name: livegoods-search
  elasticsearch:
    rest:
      uris: http://10.211.55.7:9200
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true