server:
  port: 9002
spring:
  application:
    name: livegoods-recommendation
  profiles:
    active: bannerNginx,mongodb
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true